blank_issues_enabled: false
contact_links:
  - name: Questions & support
    url: https://github.com/OWNER/REPO/discussions
    about: Please use GitHub Discussions for questions and general support.
